import os
import sys
import subprocess
import json
import re
import shutil
import time

# SUMMA-Actors config file (repo root). Passed as -c whenever Version is
# "actors"; -m still overrides its file_manager_path so the generated file
# managers are what actually run.
ACTORS_CONFIG = "summa_actors_config.json"

VERSIONS = ("non-actors", "actors")
SOLVERS = ("homegrown", "ida", "kinsol", "v3")
PRECISIONS = ("single", "double")


def runTag(version, solver, precision, tag):
    """
    The suffix every output file is stamped with. Encodes the three things a
    run can vary so their outputs sit side by side; the optional free-form
    "Tag" keeps otherwise-identical runs (e.g. a rebuild) from overwriting.
    """
    parts = [version, solver, precision]
    if tag:
        parts.append(tag)
    return "_".join(parts)


def _rss_to_mb(ru_maxrss):
    # getrusage reports ru_maxrss in bytes on macOS/BSD, kibibytes on Linux
    return ru_maxrss / (1024 * 1024) if sys.platform == "darwin" else ru_maxrss / 1024


def _exit_code(status):
    try:
        return os.waitstatus_to_exitcode(status)  # py3.9+
    except (AttributeError, ValueError):
        return os.WEXITSTATUS(status) if os.WIFEXITED(status) else -os.WTERMSIG(status)


"""
Create all of the output directories for the test cases
"""
def initOutputDirs(test_cases):
    outputDir = "./test_cases/output/"
    for test in test_cases:
        path = os.path.join(outputDir, test["name"])
        os.makedirs(path, exist_ok=True)

"""
Clean up the output directories for the test cases
"""
def cleanOutputDirs(test_cases):
    print("Cleaning output directories")
    outputDir = "./test_cases/output/"
    for test in test_cases:
        path = os.path.join(outputDir, test["name"])
        if os.path.exists(path):
            shutil.rmtree(path)  # Recursively delete directory and contents
            os.makedirs(path)    # Recreate the empty directory

"""
Clean up the file managers for the test cases
This cleans up the generated file managers for the test cases
"""
def cleanFileManagers(test_cases):
    print("Cleaning fileManagers")
    settings_dir = "./test_cases/settings/"
    for test in test_cases:
        path = os.path.join(settings_dir, test["type"])
        path = os.path.join(path, test["name"])
        if os.path.exists(path):
            file_managers = os.path.join(path, "fileManagers")
            for file_manager in os.listdir(file_managers):
                if file_manager.endswith("_test.txt"):
                    file_manager = os.path.join(file_managers, file_manager)
                    os.remove(file_manager)
"""
Setup the file managers for the test cases
"""
def setup(test_cases, precision, solver):
    # Form full path to the test_cases dir
    basedir = os.getcwd() + "/test_cases"
    settings_dir = "./test_cases/settings/"
    cleanFileManagers(test_cases)

    for test in test_cases:
        test_settings_dir = os.path.join(settings_dir, test["type"])
        test_settings_dir = os.path.join(test_settings_dir, test["name"])
        if not os.path.exists(test_settings_dir):
            print("Test case does not exist: " + test["name"])
            continue
        print("Setting up " + test["name"])
        file_managers_path = os.path.join(test_settings_dir, "fileManagers")
        for file_manager in os.listdir(file_managers_path):
            if file_manager.startswith('.'):
                continue
            sub_test = re.findall("fileManager_([^._]+).txt", file_manager)
            file_manager = os.path.join(file_managers_path, file_manager)
            print("\tSetting sub-test " + sub_test[0])
            with open(file_manager, 'r') as f:
                data = f.read()
                data = data.replace('<SOLVER>', solver)
                data = data.replace('<BASEDIR>', basedir)
                data = data.replace('<PRECISION>', precision + '_precision.txt')
            file_manager = os.path.splitext(file_manager)[0]+'_test.txt'
            with open(file_manager, 'w') as f:
                f.write(data)
                            
"""
Run the test cases
"""
def buildRunCommand(exe, file_manager, suffix, num_gru, version):
    """
    Build the command line for a single test run.

    Both builds take the same -m / -s / -g options; the "actors" build also gets
    -c ACTORS_CONFIG. -m always overrides the config's file_manager_path, so the
    file managers generated by `init` are what actually get run.
    """
    cmd = [exe, "-m", file_manager, "-s", suffix]
    if version == "actors":
        cmd += ["-c", os.path.abspath(ACTORS_CONFIG)]
    cmd += ["-g", "1", num_gru]
    #cmd += ["-p", "t"] # print timestep
    return cmd


def runOne(cmd, log_file_path):
    """Run one test, capturing stdout to a log and measuring wall time + peak RSS."""
    t0 = time.perf_counter()
    with open(log_file_path, 'w') as log_file:
        proc = subprocess.Popen(cmd, stdout=log_file)
        _, status, ru = os.wait4(proc.pid, 0)
    proc.returncode = _exit_code(status)  # let Popen know it finished
    return proc.returncode, time.perf_counter() - t0, _rss_to_mb(ru.ru_maxrss)


def runTest(test_cases, summa_exe, meta, suffix):
    print("Running test cases (" + suffix + ")")
    base_dir = os.getcwd()
    output_path = os.path.join(base_dir, "test_cases/output")
    print(base_dir)
    print(output_path)
    for test in test_cases:
        num_gru = "25" if test["type"] == "multiGruTestCases" else "1"
        settings_dir = os.path.join(base_dir, "test_cases/settings")
        settings_dir = os.path.join(settings_dir, test["type"])
        settings_dir = os.path.join(settings_dir, test["name"])
        print("Running", test["name"])
        file_managers_path = os.path.join(settings_dir, "fileManagers")
        for file_manager in os.listdir(file_managers_path):
            if file_manager.endswith("_test.txt"):
                file_manager = os.path.join(file_managers_path, file_manager)
                print("\tRunning file manager " + file_manager)
                sub_test = re.findall("fileManager_([^_]+)_test.txt", file_manager)[0]
                out_dir = os.path.join(output_path, test["name"])
                log_file_path = os.path.join(out_dir, "log_" + sub_test + "_" + suffix + ".txt")
                cmd = buildRunCommand(summa_exe, file_manager, suffix, num_gru, meta["version"])
                rc, wall_s, rss_mb = runOne(cmd, log_file_path)
                stats = dict(meta, test=test["name"], subtest=sub_test, suffix=suffix,
                             wall_s=round(wall_s, 3), max_rss_mb=round(rss_mb, 1),
                             returncode=rc)
                with open(os.path.join(out_dir, "time_" + sub_test + "_" + suffix + ".json"), 'w') as sf:
                    json.dump(stats, sf, indent=2)
                print(f"Test {test['name']} exit code was: {rc}  "
                      f"({wall_s:.1f} s, {rss_mb:.0f} MB peak)")


def pickExecutable(settings, version):
    """
    "Executables" maps Version ("non-actors" / "actors") to an exe path. List
    only the one you use if you only run one. Returns the path or None.
    """
    exes = settings.get('Executables')
    if not isinstance(exes, dict) or version not in exes:
        print("No \"Executables\" entry for Version '" + version + "'")
        return None
    if version == "actors" and not os.path.isfile(os.path.abspath(ACTORS_CONFIG)):
        print("Running 'actors' but " + ACTORS_CONFIG + " is missing")
        return None
    return exes[version]


def applyRunOverrides(tokens, version, solver, precision):
    """
    `run` takes any number of Version / Solver / Precision values as bare
    tokens (e.g. `run actors ida`) and overrides that axis for this run only.
    The three value sets do not overlap, so each token maps to exactly one axis.
    """
    for tok in tokens:
        if tok in VERSIONS:
            version = tok
        elif tok in SOLVERS:
            solver = tok
        elif tok in PRECISIONS:
            precision = tok
        else:
            print("Unknown run option '" + tok + "' "
                  "(expected a Version, Solver or Precision value)")
            return None
    return version, solver, precision


def expandTestList(requested):
    with open("test_inventory.json", "r") as inventory_file:
        inventory = json.load(inventory_file)['tests']
    if 'all' in requested:
        return list(inventory)
    groups = ('syntheticTestCases', 'multiGruTestCases', 'wrrPaperTestCases')
    out = []
    for name in requested:
        if name in groups:
            out += [t for t in inventory if t['type'] == name and t not in out]
        else:
            out += [t for t in inventory if t['name'] == name and t not in out]
    return out


def main():
    with open("settings.json", "r") as settings_file:
        settings = json.load(settings_file)
    settings.setdefault('Precision', 'double')
    settings.setdefault('Solver', 'homegrown')
    settings.setdefault('Version', 'non-actors')
    settings.setdefault('Tag', '')

    version, solver, precision = settings['Version'], settings['Solver'], settings['Precision']
    tag = settings['Tag']
    test_list = expandTestList(settings['Test_List'])

    if len(sys.argv) < 2:
        return
    cmd = sys.argv[1]

    if cmd == "clean":
        cleanOutputDirs(test_list)
        cleanFileManagers(test_list)
    elif cmd == "run":
        applied = applyRunOverrides(sys.argv[2:], version, solver, precision)
        if applied is None:
            return
        version, solver, precision = applied
        if version not in VERSIONS:
            print("Version must be one of: " + ", ".join(VERSIONS))
            return
        exe = pickExecutable(settings, version)
        if not exe:
            return
        initOutputDirs(test_list)
        setup(test_list, precision, solver)  # (re)generate file managers for THIS run
        meta = {"version": version, "solver": solver, "precision": precision, "tag": tag}
        runTest(test_list, exe, meta, runTag(version, solver, precision, tag))
    else:
        print("Invalid argument")
        print("Valid arguments are: run [<version>|<solver>|<precision> ...], clean")
    
if __name__ == "__main__":
    main()